name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        deno: [canary]
        os: [macOS-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: false

      - name: Set up Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.x.x

      - name: Format TS
        run: deno fmt --check

      - name: Run tests canary
        run: deno test --allow-all
